Artifact: error_report
Generated: 2025-07-16 19:36:47
Experiment: 20250716_193638
==================================================

{
  "error": "stack expects each tensor to be equal size, but got [236928] at entry 0 and [200298] at entry 1",
  "failed_step": "training",
  "traceback": "Traceback (most recent call last):\n  File \"/home/sei/repo/topology-control/src/CPipelineOrchestrator.py\", line 52, in run\n    self._train_model_step(pipeline_state)\n  File \"/home/sei/repo/topology-control/src/CPipelineOrchestrator.py\", line 186, in _train_model_step\n    training_results = self.model_trainer.train_and_validate(model)\n  File \"/home/sei/repo/topology-control/src/CModelTrainer.py\", line 157, in train_and_validate\n    train_loss = self._run_epoch(\n  File \"/home/sei/repo/topology-control/src/CModelTrainer.py\", line 218, in _run_epoch\n    for batch_idx, (inputs, targets) in enumerate(data_loader):\n  File \"/home/sei/miniconda3/envs/topology-control/lib/python3.10/site-packages/torch/utils/data/dataloader.py\", line 733, in __next__\n    data = self._next_data()\n  File \"/home/sei/miniconda3/envs/topology-control/lib/python3.10/site-packages/torch/utils/data/dataloader.py\", line 789, in _next_data\n    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration\n  File \"/home/sei/miniconda3/envs/topology-control/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py\", line 55, in fetch\n    return self.collate_fn(data)\n  File \"/home/sei/miniconda3/envs/topology-control/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py\", line 398, in default_collate\n    return collate(batch, collate_fn_map=default_collate_fn_map)\n  File \"/home/sei/miniconda3/envs/topology-control/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py\", line 211, in collate\n    return [\n  File \"/home/sei/miniconda3/envs/topology-control/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py\", line 212, in <listcomp>\n    collate(samples, collate_fn_map=collate_fn_map)\n  File \"/home/sei/miniconda3/envs/topology-control/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py\", line 155, in collate\n    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)\n  File \"/home/sei/miniconda3/envs/topology-control/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py\", line 272, in collate_tensor_fn\n    return torch.stack(batch, 0, out=out)\nRuntimeError: stack expects each tensor to be equal size, but got [236928] at entry 0 and [200298] at entry 1\n"
}